#!/bin/sh

printf '%10s|%5s|%50s|%-10s\n' "Transport" "EID" "UUID" "Supported MCTP Types"
SERVICES=$(busctl list --no-pager | awk '{print $1}' | grep xyz.openbmc_project.MCTP.Control)

for SERVICE in $SERVICES; do
    # Use busctl to get the object tree for the service and extract the object paths
    OBJECTS=$(busctl tree "$SERVICE" | grep "/xyz/openbmc_project/mctp/0/" | awk -F' |-' '{print $NF}')

    # Loop through each object path
    for OBJECT_PATH in $OBJECTS; do
        if [ -n "$OBJECT_PATH" ]; then
            ENABLED="true"
            # Get all interfaces for the object
            INTERFACES=$(busctl introspect "$SERVICE" "$OBJECT_PATH" | grep "interface" | awk '{print $1}')

            # Loop through each interface
            for INTERFACE in $INTERFACES; do
                if [ "$INTERFACE" = "xyz.openbmc_project.MCTP.Binding" ]; then
                    BINDING=$(busctl get-property "$SERVICE" "$OBJECT_PATH" "$INTERFACE" BindingType | awk '{print $2}' | awk -F '.' '{print $NF}')
                    BINDING="${BINDING%?}"
                elif [ "$INTERFACE" = "xyz.openbmc_project.Object.Enable" ]; then
                    ENABLED=$(busctl get-property "$SERVICE" "$OBJECT_PATH" "$INTERFACE" Enabled | awk '{print $2}')
                elif [ "$INTERFACE" = "xyz.openbmc_project.Common.UUID" ]; then
                    UUID=$(busctl get-property "$SERVICE" "$OBJECT_PATH" "$INTERFACE" UUID | awk '{print $2}')
                elif [ "$INTERFACE" = "xyz.openbmc_project.MCTP.Endpoint" ]; then
                    MSG_TYPES=$(busctl get-property "$SERVICE" "$OBJECT_PATH" "$INTERFACE" SupportedMessageTypes | awk '{$1=$2=""; print $0}')
                    EID=$(busctl get-property "$SERVICE" "$OBJECT_PATH" "$INTERFACE" EID | awk '{print $2}')
                fi
            done
            if [ "$ENABLED" = "true" ]; then
                printf '%10s|%5s|%50s|%-10s\n' "$BINDING" "$EID" "$UUID" "$MSG_TYPES"
            fi
        fi
    done
done
